source 'http://cerrnerrepos.net/api/gems/rubygems/'

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 3.5'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # Code Linters
  gem 'eslint-rails', '~> 1.3', require: false
  gem 'scss_lint', '~> 0.57.0', require: false
  gem 'slim_lint', '~> 0.20', require: false
  gem 'tide-rubocop', '~> 1.0'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15', '< 4.0'
  gem 'capybara-screenshot', '~> 1.0', '>= 1.0.14'
  gem 'selenium-webdriver'
  gem 'webdrivers', '~> 4.2'

  # Used to determine test coverage
  gem 'headless', '~> 2.3', '>= 2.3.1'
  gem 'rspec-rails', '~> 3.7'
  gem 'simplecov', '~> 0.15.0', require: false
  gem 'webmock', '~> 3.3', '>= 3.3.0'

  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Use Slim for html templating (in place of ERB)
gem 'slim', '~> 3.0', '>= 3.0.7'

# React on Rails
gem 'react_on_rails', '11.3.0'

# NOTE: CWx box does not have a compiler that supports C++11, so we must use 'therubyracer' instead of 'mini_racer'
gem 'therubyracer', platforms: :ruby # was using: mini_racer

# Colorize is needed during assets:precompile routine
gem 'colorize', '~> 0.8.1'

# load environment variables from .env files
gem 'dotenv', '~> 2.2', '>= 2.2.2'

# Nokogiri is a sub-dependency, but we need to define version to help with CWx glibc issue
gem 'nokogiri', '~> 1.10.8'

# TIDE Gems
#gem 'portal-careaware_api', :path => 'vendor/portal-careaware_api' #'~> 1.1' # Careaware API
gem 'portal-dex_framework_mock', '~> 1.0', group: [:development, :test] # Mock DEx Framework
gem 'portal-hco_api', '~> 1.0' # HCO API
gem 'portal-healthelife_api', '~> 1.2' # HealtheLife API
gem 'portal-token_session_store', '~> 1.0' # Token Session Store
gem 'tide-models', '~> 1.1'
gem 'tide-vault_api', '~> 1.1' # cerrner Vault API
