Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/Next:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Layout/EndOfLine:
  EnforcedStyle: lf

Style/FormatStringToken:
  EnforcedStyle: unannotated

Bundler/OrderedGems:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/factories/*'
    - 'spec/**/*_spec.rb'
    - 'lib/**/*.rake'

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/**/*'
