# docker-compose -f docker-compose.test.yml up test
version: '3'
services:
  test:
    image: ti.results-graphing-fhir:${TAG-default}
    command: > # Need to run npm run build first to ensure js files are up to date
      sh -c " npm run build && rspec spec"
    environment:
      - APP_HOME=/results-graphing-fhir
      - CAPYBARA_DRIVER=remote_chrome
      - REDIS_HOST=redis
      - SELENIUM_APP_HOST=http://test:3000
    volumes:
      - .:/results-graphing-fhir
      - /results-graphing-fhir/config/env/tide
      - node_modules_directory:/results-graphing-fhir/node_modules
    ports:
      - "3000"
    depends_on:
      - chrome
      - firefox
      - redis
    networks:
      - selenium-grid

  redis:
    image: redis:3.2.12
    ports:
      - "6379"
    networks:
      - selenium-grid

  hub:
    image: selenium/hub
    ports:
      - "4444"
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - selenium-grid

networks:
  selenium-grid:

volumes:
  node_modules_directory:
    driver: local
