source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  gem 'rubocop', '~> 0.76.0', require: false
  gem 'slim_lint', '~> 0.11.0', require: false
  gem 'eslint-rails', '~> 1.2', '>= 1.2.1', require: false
  gem 'scss_lint', '~> 0.52.0', require: false
  gem 'colorize', '~> 0.8.1', require: false

  gem 'capybara', '~> 3.29', '>= 3.29.0'
  gem 'capybara-screenshot', '~> 1.0', '>= 1.0.14'
  gem 'selenium-webdriver', '~> 3.142', '>= 3.142.6'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.2'
  gem 'headless', '~> 2.3', '>= 2.3.1'
  gem 'simplecov', '~> 0.13.0', require: false
  gem 'guard-rspec', '~> 4.7', '>= 4.7.3', require: false
  gem 'webmock', '~> 3.0', '>= 3.0.1'
  gem 'vcr', '~> 3.0', '>= 3.0.3'
  gem 'pry', '~> 0.10.4'
  gem 'timecop', '~> 0.8.1'
  gem 'factory_bot_rails', '~> 5.2.0'
  gem 'faker', '~> 2.12.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # Front-end to view VCR cassettes
  gem 'mr_video', '~> 1.0', '>= 1.0.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# FHIR client support
gem 'fhir_services', git: 'https://github.cerrner.com/till/Fhir-Services-Gem.git', tag: '1.1.5'

# Session and Redis support
gem 'redis-rails', '~> 5.0', '>= 5.0.1'

# Use Slim for html templating (in place of ERB)
gem 'slim', '~> 3.0', '>= 3.0.7'

# Engines
gem 'fhir-auth_engine', git: 'https://github.cerrner.com/till/fhir-auth_engine.git', tag: '1.0.2'

# Integrate webpack
gem 'webpack-rails', '~> 0.9.10'

# Natural language parser for elapsed time
gem 'chronic_duration', '~> 0.10.6'

# web request throttling
gem 'slowweb'

gem 'rx_nav', git: 'https://github.cerrner.com/till/RxNav-Gem.git', tag: 'v1.0.0'

# load environment variables from .env files
gem 'dotenv', '~> 2.2', '>= 2.2.1'

# cerrner Vault API
gem 'tide-vault_api', git: 'https://github.cerrner.com/till/tide-vault_api.git', tag: '1.1.0'
